homepage:
    pattern: /
    defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }

app_blogposts_index:
    pattern: '/blogposts'
    defaults: { _controller: 'App:BlogPosts:indexAction' }
    requirements: { _method: 'GET' }

app_blogposts_new:
    pattern: '/blogposts/new'
    defaults: { _controller: 'App:BlogPosts:newAction' }
    requirements: { _method: 'GET|POST' }

app_blogposts_show:
    pattern: '/blogposts/{id}'
    defaults: { _controller: 'App:BlogPosts:showAction' }
    requirements: { _method: 'GET' }

app_blogposts_edit:
    pattern: '/blogposts/{id}/edit'
    defaults: { _controller: 'App:BlogPosts:editAction' }
    requirements: { _method: 'GET|PUT' }

app_blogposts_delete:
    pattern: '/blogposts/{id}'
    defaults: { _controller: 'App:BlogPosts:deleteAction' }
    requirements: { _method: 'DELETE' }
